#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"


VENV_DIR="venv"
DB_NAME="odoo-soup"

if [ "$#" -eq 0 ]; then
    echo "Usage:"
    echo "odoo-soup <table name>"
    exit 1
fi

if [ ! -d "$SCRIPT_DIR/$VENV_DIR" ]; then
    echo "No venv detected, i shall make one for you and install the requirements teehee..."
    ORIGINAL_CWD=$(pwd)
    cd "$SCRIPT_DIR"
    python3 -m venv "$VENV_DIR"
    echo "Installing requirements from requirements.txt..."
    "$VENV_DIR/bin/pip" install -r requirements.txt
    cd "$ORIGINAL_CWD"
fi

if ! psql -lqt | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
    echo "Database '$DB_NAME' does not exist yet. I shall make now teehee..."
    createdb "$DB_NAME"
fi

"$SCRIPT_DIR/$VENV_DIR/bin/python" "$SCRIPT_DIR/main.py" "$@" "$SCRIPT_DIR"
