#!/bin/bash

VENV_DIR="venv"
DB_NAME="odoo-soup"

if [ "$#" -eq 0 ]; then
    echo "Usage:"
    echo "odoo-soup <table name>"
    # You can exit the script or show usage instructions here.
    exit 1
fi

# Check if the virtual environment directory exists.
if [ ! -d "$VENV_DIR" ]; then
    echo "No venv detected, i shall make one for you and install the requirements teehee..."

    # Create the virtual environment
    python3 -m venv "$VENV_DIR"

    echo "Installing requirements from requirements.txt..."
    # Check if requirements.txt exists and install from it
    "$VENV_DIR/bin/pip" install -r requirements.txt

fi


if ! psql -lqt | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
    echo "Database '$DB_NAME' does not exist yet. I shall make now teehee..."
    createdb "$DB_NAME"
fi

"$VENV_DIR/bin/python" main.py "$@"

exit 0
